# Generated by Django 3.1.7 on 2021-04-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongdamData1H',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(db_column='DT')),
                ('whumi', models.FloatField(blank=True, db_column='Whumi', null=True)),
                ('wwind', models.FloatField(blank=True, db_column='Wwind', null=True)),
                ('s0a', models.FloatField(blank=True, db_column='S0a', null=True)),
                ('s0b', models.FloatField(blank=True, db_column='S0b', null=True)),
                ('s0c', models.FloatField(blank=True, db_column='S0c', null=True)),
                ('s1a', models.FloatField(blank=True, db_column='S1a', null=True)),
                ('s1b', models.FloatField(blank=True, db_column='S1b', null=True)),
                ('s1c', models.FloatField(blank=True, db_column='S1c', null=True)),
                ('s2a', models.FloatField(blank=True, db_column='S2a', null=True)),
                ('s2b', models.FloatField(blank=True, db_column='S2b', null=True)),
                ('s2c', models.FloatField(blank=True, db_column='S2c', null=True)),
                ('s3a', models.FloatField(blank=True, db_column='S3a', null=True)),
                ('s3b', models.FloatField(blank=True, db_column='S3b', null=True)),
                ('s3c', models.FloatField(blank=True, db_column='S3c', null=True)),
                ('avg', models.FloatField(blank=True, db_column='Avg', null=True)),
                ('temp', models.FloatField(blank=True, db_column='Temp', null=True)),
                ('humi', models.FloatField(blank=True, db_column='Humi', null=True)),
                ('result', models.CharField(blank=True, db_column='Result', max_length=50, null=True)),
            ],
            options={
                'db_table': 'songdam_data_1h',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_date', models.DateTimeField(blank=True, null=True)),
                ('s0a', models.FloatField(blank=True, db_column='S0a', null=True)),
                ('s0b', models.FloatField(blank=True, db_column='S0b', null=True)),
                ('s0c', models.FloatField(blank=True, db_column='S0c', null=True)),
                ('s1a', models.FloatField(blank=True, db_column='S1a', null=True)),
                ('s1b', models.FloatField(blank=True, db_column='S1b', null=True)),
                ('s1c', models.FloatField(blank=True, db_column='S1c', null=True)),
                ('s2a', models.FloatField(blank=True, db_column='S2a', null=True)),
                ('s2b', models.FloatField(blank=True, db_column='S2b', null=True)),
                ('s2c', models.FloatField(blank=True, db_column='S2c', null=True)),
                ('s3a', models.FloatField(blank=True, db_column='S3a', null=True)),
                ('s3b', models.FloatField(blank=True, db_column='S3b', null=True)),
                ('s3c', models.FloatField(blank=True, db_column='S3c', null=True)),
                ('avg', models.FloatField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'test_result',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestResult1H',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_date', models.DateTimeField(blank=True, null=True, unique=True)),
                ('s0a', models.FloatField(blank=True, db_column='S0a', null=True)),
                ('s0b', models.FloatField(blank=True, db_column='S0b', null=True)),
                ('s0c', models.FloatField(blank=True, db_column='S0c', null=True)),
                ('s1a', models.FloatField(blank=True, db_column='S1a', null=True)),
                ('s1b', models.FloatField(blank=True, db_column='S1b', null=True)),
                ('s1c', models.FloatField(blank=True, db_column='S1c', null=True)),
                ('s2a', models.FloatField(blank=True, db_column='S2a', null=True)),
                ('s2b', models.FloatField(blank=True, db_column='S2b', null=True)),
                ('s2c', models.FloatField(blank=True, db_column='S2c', null=True)),
                ('s3a', models.FloatField(blank=True, db_column='S3a', null=True)),
                ('s3b', models.FloatField(blank=True, db_column='S3b', null=True)),
                ('s3c', models.FloatField(blank=True, db_column='S3c', null=True)),
                ('avg', models.FloatField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'test_result_1h',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestResult1HHumi',
            fields=[
                ('result_date', models.DateTimeField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('s0a', models.FloatField(blank=True, db_column='S0a', null=True)),
                ('s0b', models.FloatField(blank=True, db_column='S0b', null=True)),
                ('s0c', models.FloatField(blank=True, db_column='S0c', null=True)),
                ('s1a', models.FloatField(blank=True, db_column='S1a', null=True)),
                ('s1b', models.FloatField(blank=True, db_column='S1b', null=True)),
                ('s1c', models.FloatField(blank=True, db_column='S1c', null=True)),
                ('s2a', models.FloatField(blank=True, db_column='S2a', null=True)),
                ('s2b', models.FloatField(blank=True, db_column='S2b', null=True)),
                ('s2c', models.FloatField(blank=True, db_column='S2c', null=True)),
                ('s3a', models.FloatField(blank=True, db_column='S3a', null=True)),
                ('s3b', models.FloatField(blank=True, db_column='S3b', null=True)),
                ('s3c', models.FloatField(blank=True, db_column='S3c', null=True)),
                ('avg', models.FloatField(blank=True, null=True)),
                ('humi', models.FloatField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'test_result_1h_humi',
                'managed': False,
            },
        ),
    ]
